### ISSUE TITLE
Add docker-compose.yml for hosting and reverse proxying with Traefik

### ISSUE THREAD

**Issue by AmreshSinha** [AmreshSinha/Covid19-API#7]
Add a docker-compose.yml for hosting with docker and reverse proxying via Traefik. 
You can follow this guide for hosting Traefik and running a sample application: 
https://fossian.com/self-host-ghost-blog-mysql-traefik/

**Comment by Purvarth** [comment]
I have worked with docker in past. Can I work on this?

**Comment by AmreshSinha** [comment]
> I have worked with docker in past. Can I work on this?

Sure 👍
